=== PavloZaviazun/JavaCoreCourse/input.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="https://epam.com/practice7"
            elementFormDefault="qualified">
    <xsd:element name="cinema">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="movie" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="id" type="xsd:positiveInteger"/>
                            <xsd:element name="title" type="xsd:string"/>
                            <xsd:element name="year" type="xsd:gYear"/>
                            <xsd:element name="genre" maxOccurs="3">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="Horror"/>
                                        <xsd:enumeration value="Comedy"/>
                                        <xsd:enumeration value="Thriller"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== PavloZaviazun/JavaCoreCourse/input.xml
<?xml version="1.0" encoding="UTF-8" ?>
<practice7:cinema xmlns:practice7="https://epam.com/practice7"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://epam.com/practice7 input.xsd">
    <practice7:movie>
        <practice7:id>1</practice7:id>
        <practice7:title>"The Shawshank Redemption"</practice7:title>
        <practice7:year>1994</practice7:year>
        <practice7:genre>Horror</practice7:genre>
    </practice7:movie>
    <practice7:movie>
        <practice7:id>2</practice7:id>
        <practice7:title>"The Godfather"</practice7:title>
        <practice7:year>1972</practice7:year>
        <practice7:genre>Comedy</practice7:genre>
    </practice7:movie>
    <practice7:movie>
        <practice7:id>3</practice7:id>
        <practice7:title>"The Dark Knight"</practice7:title>
        <practice7:year>2008</practice7:year>
        <practice7:genre>Thriller</practice7:genre>
    </practice7:movie>
</practice7:cinema>
